### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dextonanderson** [henkelmax/simple-voice-chat#196]
Hi,

Does this mod have a license? Would I be able to fork this mod and modify it for my own uses either non-commercially or commercially?

Thanks

**Comment by henkelmax** [comment]
If you use it privately, its fine.
If you want to publish it you need to talk to me about it.

**Comment by dextonanderson** [comment]
Yes, I plan to use it privately for a server. Eg. Mod is distributed by me exclusive to (and will only work on) my server. We won't be publishing it for general use on curse, etc.

**Comment by henkelmax** [comment]
Then it is perfectly fine :)
If you add something that could benefit others, you could create a pull request.

**Comment by nfitzen** [comment]
@henkelmax if you don't add a license, no one can make modifications without risk of takedowns and lawsuits, and, if you accept contributions from anyone, ["nobody" starts including you, too](https://choosealicense.com/no-permission/). 

If you care about sharing improvements, and are afraid someone might not contribute their modifications back, [the GNU GPL version 3 or later][1] might be a good license fit, if you haven't already checked that out?

(You might want to also add [`GPL-3.0-linking-exception`] with "Minecraft" and "Minecraft EULA" filled in, if using it.)

[1]: https://www.gnu.org/licenses/gpl.html "SPDX-License-Identifier: GPL-3.0-or-later"

[`GPL-3.0-linking-exception`]: https://spdx.org/licenses/GPL-3.0-linking-exception.html "GPL-3.0 Linking Exception"

**Comment by henkelmax** [comment]
Without a license people can still fork the repository and make PRs.

> If you publish your source code in a public repository on GitHub, according to the Terms of Service, other users of GitHub have the right to view and fork your repository.

Source: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository

**Comment by nfitzen** [comment]
@henkelmax a few things:

1. choosealicense (the link I cited for "nobody starts including you, too") is [literally made by GitHub](https://github.com/github/choosealicense.com), so I'd consider that a decent authoritative source.
2. "view and fork" does not include PRs, modification, download, redistribution, or use in a YouTube video, among any other monopoly that copyright holders have.

**Comment by henkelmax** [comment]
Sorry, but I will not include a license. I had too many bad experiences with people just reuploading the mod and making money off of it.

**Comment by nfitzen** [comment]
> I had too many bad experiences with people just reuploading the mod and making money off of it.

@henkelmax hmm. Yeah. That's a tricky one. It's definitely scummy. I can see where you're coming from.

The only thing I can say is that the GNU GPL requires any re-uploaders to give source code and give credit if they do make money off of the mod (via a copyright notice), and I doubt any of those reuploaders will do that. (It has to be in the exact same page from which users download the re-uploaded version. They'll likely just end up linking to this GitHub page.)

This'll be my last comment, since I get where you're coming from. Sorry if I came off a bit pushy; I just think it'd be a boon for the MC community if this mod were free (libre) software.

**Comment by WilloIzCitron** [comment]
If you don't want to add any open source licenses and keep it All Rights Reserved, You need to make the EULA by asking the lawyer to collaborate in formation/creation of the EULA. That's the last option to keeping your mod open source and protect the mod from redistribution (combating the reuploader/reposter)

**Comment by jan-Sanku** [comment]
please consider adding a noncommercial license then. ANY will do. PolyForm NC seems like a great candidate (https://polyformproject.org/licenses/noncommercial/1.0.0)

this will prevent people from "just reuploading the mod and making money off of it", which seems to be your goal. a noncommercial license will do this job just as well as All Rights Reserved (ARR). you do not gain any benefit in this regard from keeping this project ARR.

with your main concern addressed, here is why the project would heavily benefit from having ANYTHING other than ARR as its license:
- while you may have a license file that says you reserve all rights, there is no clause about contributors' copyrights, so everyone who contributes code to this project *will continue to be the copyright holder of that code.* while it's true that many jurisdictions rule that by creating a PR, you grant an implicit license for the project owner to use that code, but the scope of this implicit license is entirely undefined. not only can contributors end up in legal trouble, **you could too** (i am not a lawyer and this is not legal advice, but the fact is that you currently do not own all of the code in this project)
- therefore, adding a noncommercial license will protect both you and your contributors, while still disallowing 3rd party commercial use.
- you won't be around forever. maybe you won't feel like modding anymore, or maybe worse, but either way, you cannot guarantee that the project will be maintained in the unforeseeable future. now, i don't know about you, but with a mod as beloved as this one, i would want others to be able to carry on with the project. commercially or not (and it would be noncommercial here), one of the greatest things in minecraft modding is the fact that *most* mods can be forked and kept alive once they're inevitably abandoned. except for this one. wouldn't you want people to have the ability to keep using this truly influential project in the future? and again, they wouldn't take away your ownership or make any money off it! you're still the owner, no matter what.
- now, you might say that you can just appoint someone to take over the project for you (assuming you will be physically capable of it once necessary, which is not a given), but because of the aforementioned copyright issues, you don't actually own the entire project. again, not a lawyer, but from what i can tell, such a transfer only "MIGHT" be defensible, but might also not be.


at least, please add a Contributor License Agreement (CLA) to transfer copyright of all future contributions to your name. that should help prevent legal issues for all involved parties, and is the only real way for you to *actually* reserve all the rights. still, any sort of real license would greatly benefit you and your contributors, in my opinion.

your project of course, but please be aware of what your decision actually entails when taking contributions from others, as well as what the project's future might look like.
