### ISSUE TITLE
BadPaddingException

### ISSUE THREAD

**Issue by Moocow9m** [henkelmax/simple-voice-chat#243]
Please read the FAQ before submitting a bug report!

Bug description
Randomly, while voice activation is on, it will throw this exception and sometimes crash the client. It has not been tested without krypton, but is random enough to be hard to replicate, so a test could not be conducted. Player can also be alone on the server and exception will still happen.

Steps to reproduce the issue
Unknown

Expected behavior
Packets that are incomplete or corrupted should be handled in a try catch and probably discarded rather than crashing the client.

Log files
https://gist.github.com/Moocow9m/82450152b278f487555a524d88e2288c

Versions

1.17
Fabric 0.11.6
1.4.4
Other mods
krypton@0.1.3
fabric-api-0.36.0+1.17

**Comment by henkelmax** [comment]
Please provide the full log files of your client and server.

**Comment by Xicad** [comment]
I'm having the same issue as Moocow9m, here are my log files.
Server: https://gist.github.com/Xicad/36b8cbc49f0e849480cda37850c3e978
Client: https://gist.github.com/Xicad/a9da82e646df258505432d228cc6a443

**Comment by henkelmax** [comment]
This happens if traffic from another application arrives on the server.
Sometimes this is caused by using VPNs or other stuff that can mess with UDP packets.
But it seems to work for you and if there are only occasionally errors, you can ignore them.
If these errors occur very regularly, I would advise switching the port or in some cases the MC hoster.
