### ISSUE TITLE
Badly compressed packet size of 2 is below server threshold of 256

### ISSUE THREAD

**Issue by FBDKPlus** [henkelmax/simple-voice-chat#274]
Badly compressed packet size of 2 is below server threshold of 256

[00:08:57] [Server thread/INFO]: SuperMenu lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2 is below server threshold of 256

After installing this plug-in, it is difficult to connect to the server. Always remind the above

**Comment by henkelmax** [comment]
This is an issue when the server is in offline mode.
This bug won't get fixed as we don't support pirating the game.

**Comment by laontme** [comment]
> This is an issue when the server is in offline mode.

@henkelmax, can you explain why is this happening?

**Comment by henkelmax** [comment]
> > This is an issue when the server is in offline mode.
> 
> @henkelmax, can you explain why is this happening?

This is the login networking of MC:
https://wiki.vg/Protocol#Login

The voice chat login packet is sent when [Login Start](https://wiki.vg/Protocol#Login_Start) is sent.
Normally there is enough time until [Set Compression](https://wiki.vg/Protocol#Set_Compression) is sent, but because offline mode does not send the [Encryption Request](https://wiki.vg/Protocol#Encryption_Request) packet because offline mode is unencrypted, there is a race condition, because the packet would arrive uncompressed, but compression is already set at that point.
