### ISSUE TITLE
Add PlaceholdersAPI support for Bukkit/Spigot

### ISSUE THREAD

**Issue by c1oneman** [henkelmax/simple-voice-chat#335]
**Is your feature request related to a problem? Please describe.**
I would love to be able to use talking status in the TAB list on my server or use it in scripting to send players without voicechat installed notifications to get it installed. PlaceholderAPI is a great system and used widely on spigot servers.

**Describe the solution you'd like**
I would like a few placeholders. 
%player_isChatting%
%player_hasSimpleVoiceChatInstalled%
%player_isMuted%

**Comment by henkelmax** [comment]
I added PlaceholderAPI support.
But not the way you suggested it:
Placeholders are like the name suggests **placeholders**, so boolean values like `ismuted` would make no sense here.

I added:
- `voicechat_prefix_uses_voicechat`
- `voicechat_prefix_no_voicechat`
- `voicechat_prefix_disabled`

These are prefixes to change the color of a text. You can change the default colors in the `translations.yml`.

`player_isChatting` is not possible since this value is completely client side.

**Comment by Gabo6480** [comment]
Is is it possible to add a placeholder for the voicechat icons that should appear beside a player's name tag?
![image](https://user-images.githubusercontent.com/60194781/183222337-ac374ea1-e6a1-44e4-bf41-4daa9a72de3d.png)
I'm using the TAB plugin, and the "unlimited-nametag-mode" overrides the player's name tag, which effectively hides the icon.
From my knowledge on PAPI, I believe it would have to be a relational placeholder since it should also check if the player looking at another player has the mod installed.

**Comment by Gabo6480** [comment]
Or, at least, placeholder to access a value that represents the current icon that would have to be displayed, and another one that returns whether or not a player has voicechat installed

**Comment by N3P1X69** [comment]
https://github.com/N3P1X69/VoiceChat-ICON
