### ISSUE TITLE
[Mod compatibility] voice animation support for Customizable Player Models

### ISSUE THREAD

**Issue by netcore10** [henkelmax/simple-voice-chat#406]
**Is your feature request related to a problem? Please describe.**
Customizable Player Models has an API to animate when the player speaks
Can you please add compatibility with this mod?

**Describe alternatives you've considered**
No voice mod has added functionality yet, sinse simple voice chat is the simplest and most approachable, i thought i'd request it.

**Additional context**
API documentation: https://github.com/tom5454/CustomPlayerModels/wiki/API-documentation#voice-animation
Mod src: https://github.com/tom5454/CustomPlayerModels

**Comment by henkelmax** [comment]
Simple Voice Chat generally doesn't add compatibility with other mods. You can either contact the devs of the custom player models mod to add compatibility, or you can create a compatibility mod.
Because of this, Simple Voice Chat has an API: https://github.com/henkelmax/simple-voice-chat/tree/1.18.2/api

**Comment by RippleRose** [comment]
so, from what i understand...

 you both have APIs and neither is willing to work with the other because it's too much work to add a support function for custom player models?

seems pretty moot to have an API if you aren't willing to work with other devs and find a middle ground.

leaving it up to the players to figure out feels down right sloppy.

**Comment by henkelmax** [comment]
It does not make sense to put such a feature in any of both mods. A compatibility mod is perfectly fine for this. Adding a dependency of another complex mod into a project will always make porting to newer versions slower. Thats literally the middle ground. 
I am not interested in creating this compatibility mod. I have enough other stuff to do. I am maintaining about 50 other mods. It feels pretty ungrateful that you basically "demand" for this compatibility to exist.

I made the API, so everyone can do whatever they want.
