### ISSUE TITLE
Anti virus flagging mod

### ISSUE THREAD

**Issue by Latino2k7** [henkelmax/simple-voice-chat#673]
### Confirmation

- [X] I have read the wiki

### Bug description

my antivirus detect a tronjan 

### Minecraft version

1.20.4

### Mod/Plugin version

1.20.4-2.5.8

### Mod/Plugin loader and version

fabric loader 0.15.6

### Steps to reproduce

n/a

### Log files

n/a

### Screenshots

![Screenshot 2024-03-07 052753](https://github.com/henkelmax/simple-voice-chat/assets/37272834/51aebf3a-0477-4664-90a3-d329d7b70455)

**Comment by vico93** [comment]
Same here. Never had a similar false-positive with a Minecraft before.

**Comment by henkelmax** [comment]
This mod ships native code, that might alert some antivirus software. You can see the source code of everything that's used on GitHub:
https://github.com/henkelmax/opus4j
https://github.com/henkelmax/lame4j
https://github.com/henkelmax/rnnoise4j

There's not much I can do about antivirus software somehow flagging it.
I'd suggest contacting your antivirus provider about that, since its either a false-positive or you downloaded the mod from a malicious site.

CurseForge and Modrinth both have tools in place to check the jars for malware and everything goes through fine. So please double check that you've downloaded the mod from official sources.

**Comment by henkelmax** [comment]
I also just checked the file with VirusTotal and there is nothing.
![image](https://github.com/henkelmax/simple-voice-chat/assets/13237524/a33c6e25-6df5-4c1f-a76e-cf9d8717cbae)

https://www.virustotal.com/gui/file/1a774f7c9e0440c06ab422720de20ffc3e89756ac753b2fab755da70effe45b1
